component_depth: 8
languages:
- name: java
  production:
    exclude:
      - /app/src/test/.*\.java
      - /app/src/androidTest/.*\.java
      - /app/src/commonTest/.*\.java
  test:
    include:
      - /app/src/test/.*\.java
      - /app/src/androidTest/.*\.java
      - /app/src/commonTest/.*\.java