sudo: false

language: android
jdk: oraclejdk8

env:
  global:
    - GRADLE_OPTS="-Xms128m"

android:
  components:
    - tools
    - platform-tools
    - tools
    - android-19
    - android-25
    - build-tools-25.0.2
    - extra-android-m2repository
    - extra-android-support
    - sys-img-armeabi-v7a-android-19

before_script:
  - sudo service postgresql stop || true
  - sudo service mysql stop || true
  - sudo service memcached stop || true
  - sudo service bootlogd stop || true
  - sudo service elasticsearch stop || true
  - sudo service mongodb stop || true
  - sudo service neo4j stop || true
  - sudo service cassandra stop || true
  - sudo service riak stop || true
  - sudo service rsync stop || true
  - sudo service x11-common stop || true
  - echo no | android create avd --force -n test -t android-19 --abi armeabi-v7a
  - ./gradlew dependencies

script:
  - ./gradlew --no-daemon --stacktrace clean
  - ./gradlew --no-daemon --stacktrace build -PdisablePreDex -PwithDexcount -Dscan
  - emulator -avd test -no-window &
  - android-wait-for-emulator
  - ./gradlew --no-daemon --stacktrace connectedAndroidTest -PdisablePreDex -PwithDexcount

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle